### ISSUE TITLE
Adding Header to JSON

### ISSUE THREAD

**Issue by LeandroFranciscato** [LeandroFranciscato/tableToJSON#1]
When parsing the `<table>`, the element `<th>` is not added to the JSON object!

**Comment by MiltonAkash** [comment]
@LeandroFranciscato  I have added some part of code that takes th tag for tables as header and normal first div tags for li elements. 
https://github.com/LeandroFranciscato/tableToJSON/pull/4

**Comment by LeandroFranciscato** [comment]
It Works, I'm closing the issue.

**Comment by MiltonAkash** [comment]
Thank You
